name: Redstone Push Commit

concurrency: production

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Clone Repo
        run: |
          cd ..
          rm -rf Redstone
          git clone -q https://github.com/stickz/Redstone
        
      - name: Branch Commit History
        run: |
          git branch -D history
          git branch history 57c5c38
        continue-on-error: true

      - name: Run Chmod
        run: chmod 777 .github/scripts/build.sh

      - name: Build Stable
        run: ./.github/scripts/build.sh -v --sourcemod=1.11.0-6911 --out=build
        shell: bash

  deployment:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Build Redstone Server
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
          SKIP_EMPTY_COMMITS: true
