name: Redstone Push Commit

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clone Repo
        uses: actions/checkout@master
        
      - name: Branch Commit History
        run: |
          git branch -D history 2>/dev/null
          git branch history 6df183e

      - name: Run Chmod
        run: chmod 777 .github/scripts/build.sh

      - name: Build Stable
        run: ./.github/scripts/build.sh -v --sourcemod=1.10.0-6453 --out=build
        shell: bash
