name: Redstone Push Commit

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clone Repo
        run: git clone https://github.com/stickz/Redstone

      - name: Run Chmod
        run: chmod 777 .github/scripts/build.sh

      - name: Build Stable
        run: ./.github/scripts/build.sh -v --sourcemod=1.10.0-6453 --out=build
        shell: bash
